import React from 'react';
// ⚠️ import 时候需要指定扩展名，即加上 .js

const TENANT_ADMIN = 'TenantAdmin';
const PlatformAdmin = 'PlatformAdmin'; // 3
const SystemAdmin = 'SystemAdmin'; // 2

const data = [
  {
    id: 'grafana',
    type: 'all-product',
    text: 'Grafana',
    textEn: 'Grafana',
    column: 10,
    rankingInColumn: 20,
    tenant: false,
    isRenderSelectCurrent: false,
    children: [
      {
        id: 'grafana-1',
        text: 'Grafana',
        textEn: 'Grafana',
        tenant: false,
        isRenderSelectCurrent: false,
        children: [
          {
            id: 'grafana-home',
            text: 'Home',
            textEn: 'Home',
            pathname: '/',
            tenant: false,
            isRenderSelectCurrent: false,
          },
          {
            id: 'grafana-dashboards',
            text: 'Dashboards',
            textEn: 'Dashboards',
            tenant: false,
            isRenderSelectCurrent: false,
            children: [
              {
                id: 'grafana-dashboards-real',
                text: 'Dashboards',
                textEn: 'Dashboards',
                pathname: '/dashboards',
                tenant: false,
                isRenderSelectCurrent: false,
              },
              {
                id: 'grafana-dashboards-playlists',
                text: 'Playlists',
                textEn: 'Playlists',
                pathname: '/playlists',
                tenant: false,
                isRenderSelectCurrent: false,
              },
              {
                id: 'grafana-dashboards-snapshots',
                text: 'Snapshots',
                textEn: 'Snapshots',
                pathname: '/dashboard/snapshots',
                tenant: false,
                isRenderSelectCurrent: false,
              },
              {
                id: 'grafana-dashboards-library-panels',
                text: 'Library panels',
                textEn: 'Library panels',
                pathname: '/library-panels',
                tenant: false,
                isRenderSelectCurrent: false,
              },
            ],
          },
          {
            id: 'grafana-explore',
            text: 'Explore',
            textEn: 'Explore',
            pathname: '/explore',
            tenant: false,
            isRenderSelectCurrent: false,
          },
          {
            id: 'grafana-alerting',
            text: 'Alerting',
            textEn: 'Alerting',
            tenant: false,
            isRenderSelectCurrent: false,
            children: [
              {
                id: 'grafana-alerting-real',
                text: 'Alerting',
                textEn: 'Alerting',
                pathname: '/alerting',
                tenant: false,
                isRenderSelectCurrent: false,
              },
              {
                id: 'grafana-alerting-list',
                text: 'Alert rules',
                textEn: 'Alert rules',
                pathname: '/alerting/list',
                tenant: false,
                isRenderSelectCurrent: false,
              },
              {
                id: 'grafana-alerting-notifications',
                text: 'Contact points',
                textEn: 'Contact points',
                pathname: '/alerting/notifications',
                tenant: false,
                isRenderSelectCurrent: false,
              },
              {
                id: 'grafana-alerting-routes',
                text: 'Notification policies',
                textEn: 'Notification policies',
                pathname: '/alerting/routes',
                tenant: false,
                isRenderSelectCurrent: false,
              },
              {
                id: 'grafana-alerting-silences',
                text: 'Silences',
                textEn: 'Silences',
                pathname: '/alerting/silences',
                tenant: false,
                isRenderSelectCurrent: false,
              },
              {
                id: 'grafana-alerting-groups',
                text: 'Groups',
                textEn: 'Groups',
                pathname: '/alerting/groups',
                tenant: false,
                isRenderSelectCurrent: false,
              },
              {
                id: 'grafana-alerting-admin',
                text: 'Admin',
                textEn: 'Admin',
                pathname: '/alerting/admin',
                tenant: false,
                isRenderSelectCurrent: false,
              },
            ],
          },
          {
            id: 'grafana-connections',
            text: 'Connections',
            textEn: 'Connections',
            tenant: false,
            isRenderSelectCurrent: false,
            children: [
              {
                id: 'grafana-connections-add-new-connection',
                text: 'Add new connection',
                textEn: 'Add new connection',
                pathname: '/connections/add-new-connection',
                tenant: false,
                isRenderSelectCurrent: false,
              },
              {
                id: 'grafana-connections-datasources',
                text: 'Data sources',
                textEn: 'Data sources',
                pathname: '/connections/datasources',
                tenant: false,
                isRenderSelectCurrent: false,
              },
            ],
          },
          {
            id: 'grafana-admin',
            text: 'Administration',
            textEn: 'Administration',
            tenant: false,
            isRenderSelectCurrent: false,
            children: [
              {
                id: 'grafana-admin-real',
                text: 'Administration',
                textEn: 'Administration',
                pathname: '/admin',
                tenant: false,
                isRenderSelectCurrent: false,
              },
              {
                id: 'grafana-datasources',
                text: 'Data sources',
                textEn: 'Data sources',
                pathname: '/datasources',
                tenant: false,
                isRenderSelectCurrent: false,
              },
              {
                id: 'grafana-plugins',
                text: 'Plugins',
                textEn: 'Plugins',
                pathname: '/plugins',
                tenant: false,
                isRenderSelectCurrent: false,
              },
              {
                id: 'grafana-admin-users',
                text: 'Users',
                textEn: 'Users',
                pathname: '/admin/users',
                tenant: false,
                isRenderSelectCurrent: false,
              },
              {
                id: 'grafana-org-teams',
                text: 'Teams',
                textEn: 'Teams',
                pathname: '/org/teams',
                tenant: false,
                isRenderSelectCurrent: false,
              },
              {
                id: 'grafana-org-serviceaccounts',
                text: 'Service accounts',
                textEn: 'Service accounts',
                pathname: '/org/serviceaccounts',
                tenant: false,
                isRenderSelectCurrent: false,
              },
              {
                id: 'grafana-org',
                text: 'Default preferences',
                textEn: 'Default preferences',
                pathname: '/org',
                tenant: false,
                isRenderSelectCurrent: false,
              },
              {
                id: 'grafana-admin-settings',
                text: 'Settings',
                textEn: 'Settings',
                pathname: '/admin/settings',
                tenant: false,
                isRenderSelectCurrent: false,
              },
              {
                id: 'grafana-admin-orgs',
                text: 'Organizations',
                textEn: 'Organizations',
                pathname: '/admin/orgs',
                tenant: false,
                isRenderSelectCurrent: false,
              },
              {
                id: 'grafana-admin-upgrading',
                text: 'Stats and license',
                textEn: 'Stats and license',
                pathname: '/admin/upgrading',
                tenant: false,
                isRenderSelectCurrent: false,
              },
            ],
          },
        ],
      },
    ]
  },
];

export default data;
